/* Generated by the Makefile, dont edit manually */
#define LUA_INIT "METALUA_INIT"
#define LUA_PATH "METALUA_PATH"
#define LUA_CPATH "METALUA_CPATH"
#define LUA_PATH_DEFAULT  "./?.lua;/tmp/lua/?.lua;./?.luac;/tmp/lua/?.luac"
#define LUA_CPATH_DEFAULT "/tmp/lua/?.dylib;/tmp/lua/?/linit.dylib"
