# Bootstrapped makefiles are a PITA to get right, so metalua is simply generated by
# a shell script (also available for windows).
#
# To customize installation directories, edit metalua/src/make.{sh,bat}
#  - on windows, change DISTRIB_LIB and DISTRIB_BIN
#  - on unix, change INSTALL_LIB and INSTALL_BIN
#
# DISTRIB_LIB / INSTALL_LIB can point to an existing Lua library structure, and shouldn't
# mess it up.



# Compile everything in a staging area, by default /tmp/metalua-build.

all:
	cd src && ./make.sh



# src/make-install.sh is generated by src/make.sh, so "make install" won't work unless
# you called "make" first.

install:
	cd src && ./make-install.sh